// https://ubsicap.github.io/usfm/identification/index.html
module.exports = {
	// Chapters and Verses
	chapters: [
		{"type": "C", "regex": /^\\c\s+\d+\s*/i},
		{"type": "CA", "regex": /^\\ca\*?\s+\d*\s*/i},
		{"type": "CL", "regex": /^\\cl\s*/i},
		{"type": "CP", "regex": /^\\cp\s*/i},
		{"type": "CD", "regex": /^\\cd\s*/i},
	],
	verses: [
		{"type": "V", "regex": /^\\v\s+\d+\s*/i},
		{"type": "VA", "regex": /^\\va\*?\s+\d+\s*/i},
		{"type": "VP", "regex": /^\\vp\*?\s*/i},
	],
	// Paragraphs
	paragraphs: [
		{"type": "P", "regex": /^\\p\s*/i},
		{"type": "M", "regex": /^\\m\s*/i},
		{"type": "PO", "regex": /^\\po\s*/i},
		{"type": "PR", "regex": /^\\pr\s*/i},
		{"type": "CLS", "regex": /^\\cls\s*/i},
		{"type": "PMO", "regex": /^\\pmo\s*/i},
		{"type": "PMC", "regex": /^\\pmc\s*/i},
		{"type": "PMR", "regex": /^\\pmr\s*/i},
		{"type": "PI", "regex": /^\\pi\d*\s*/i},
		{"type": "MI", "regex": /^\\mi\s*/i},
		{"type": "NB", "regex": /^\\nb\s*/i},
		{"type": "PC", "regex": /^\\pc\s*/i},
		{"type": "PH", "regex": /^\\ph\d*\s*/i},
		{"type": "B", "regex": /^\\b\s*/i},
	],
	// Milestones
	milestones: [
		{"type": "QT", "regex": /^\\qt\d*(?:-[se])?\*?\s*/i},
		{"type": "TS", "regex": /^\\ts(?:-[se])?\*?\s*/i},
		{"type": "Z", "regex": /^\\(z(?:[\w-]*\*?)\*?)\s*/i},
		{"type": "MI_END", "regex": /^\\\*\s*/i},
	],
	// Identification
	identification: [
		{"type": "ID", "regex": /^\\id\s*/i},
		{"type": "USFM", "regex": /^\\usfm\s*/i},
		{"type": "IDE", "regex": /^\\ide\s*/i},
		{"type": "STS", "regex": /^\\sts\s*/i},
		{"type": "REM", "regex": /^\\rem\s*/i},
		{"type": "H", "regex": /^\\h\s*/i},
		{"type": "TOC", "regex": /^\\toc\d*\s*/i},
		{"type": "TOCA", "regex": /^\\toca\d*\s*/i},
	],
	// Introductions
	introductions: [
		{"type": "IMT", "regex": /^\\imt\d*\s*/i},
		{"type": "IS", "regex": /^\\is\d*\s*/i},
		{"type": "IP", "regex": /^\\ip\s*/i},
		{"type": "IPI", "regex": /^\\ipi\s*/i},
		{"type": "IM", "regex": /^\\im\s*/i},
		{"type": "IMI", "regex": /^\\imi\s*/i},
		{"type": "IPQ", "regex": /^\\ipq\s*/i},
		{"type": "IPR", "regex": /^\\ipr\s*/i},
		{"type": "IQ", "regex": /^\\iq\d*\s*/i},
		{"type": "IB", "regex": /^\\ib\s*/i},
		{"type": "ILI", "regex": /^\\ili\d*\s*/i},
		{"type": "IOT", "regex": /^\\iot\s*/i},
		{"type": "IO", "regex": /^\\io\d*\s*/i},
		{"type": "IOR", "regex": /^\\ior\*?\s*/i},
		{"type": "IQT", "regex": /^\\iqt\*?\s*/i},
		{"type": "IEX", "regex": /^\\iex\s*/i},
		{"type": "IMTE", "regex": /^\\imte\d*\s*/i},
		{"type": "IE", "regex": /^\\ie\s*/i},
	],
	// Titles, Headings, and Labels
	titles: [
		{"type": "MT", "regex": /^\\mt\d*\s*/i},
		{"type": "MTE", "regex": /^\\mte\d*\s*/i},
		{"type": "MS", "regex": /^\\ms\d*\s*/i},
		{"type": "MR", "regex": /^\\mr\s*/i},
		{"type": "S", "regex": /^\\s\d*\s*/i},
		{"type": "SR", "regex": /^\\sr\s*/i},
		{"type": "R", "regex": /^\\r\s*/i},
		{"type": "RQ", "regex": /^\\rq\*?\s*/i},
		{"type": "D", "regex": /^\\d\s*/i},
		{"type": "SP", "regex": /^\\sp\s*/i},
		{"type": "SD", "regex": /^\\sd\d*\s*/i},
	],
	// Poetry
	poetry: [
		{"type": "Q", "regex": /^\\q\d*\s*/i},
		{"type": "QR", "regex": /^\\qr\s*/i},
		{"type": "QC", "regex": /^\\qc\s*/i},
		{"type": "QS", "regex": /^\\qs\*?\s*/i},
		{"type": "QA", "regex": /^\\qa\s*/i},
		{"type": "QAC", "regex": /^\\qac\*?\s*/i},
		{"type": "QM", "regex": /^\\qm\d*\s*/i},
		{"type": "QD", "regex": /^\\qd\s*/i},
	],
	// Lists
	lists: [
		{"type": "LH", "regex": /^\\lh\s*/i},
		{"type": "LI", "regex": /^\\li\d*\s*/i},
		{"type": "LF", "regex": /^\\lf\s*/i},
		{"type": "LIM", "regex": /^\\lim\d*\s*/i},
		{"type": "LITL", "regex": /^\\litl\*?\s*/i},
		{"type": "LIK", "regex": /^\\lik\*?\s*/i},
		{"type": "LIV", "regex": /^\\liv\d*\*?\s*/i},
	],
	// Tables
	tables: [
		{"type": "TR", "regex": /^\\tr\s*/i},
		{"type": "TH", "regex": /^\\th\d*\s*/i},
		{"type": "THR", "regex": /^\\thr\d*\s*/i},
		{"type": "TC", "regex": /^\\tc\d*\s*/i},
		{"type": "TCR", "regex": /^\\tcr\d*\s*/i},
	],
	// Footnotes
	{"type": "F", "regex": /^\\f\*?\s*/i},
	// embedded in F
	{"type": "FE", "regex": /^\\fe\*?\s*/i},
	{"type": "FR", "regex": /^\\fr\s*/i},
	{"type": "FQ", "regex": /^\\fq\s*/i},
	{"type": "FQA", "regex": /^\\fqa\s*/i},
	{"type": "FK", "regex": /^\\fk\s*/i},
	{"type": "FL", "regex": /^\\fl\s*/i},
	{"type": "FW", "regex": /^\\fw\s*/i},
	{"type": "FP", "regex": /^\\fp\s*/i},
	{"type": "FV", "regex": /^\\fv\*?\s*/i},
	{"type": "FT", "regex": /^\\ft\s*/i},
	{"type": "FDC", "regex": /^\\fdc\*?\s*/i},
	{"type": "FM", "regex": /^\\fm\*?\s*/i},
	// X-refs
	{"type": "X", "regex": /^\\x\*?\s*/i},
	// embedded in X
	{"type": "XO", "regex": /^\\xo\s*/i},
	{"type": "XK", "regex": /^\\xk\s*/i},
	{"type": "XQ", "regex": /^\\xq\s*/i},
	{"type": "XT", "regex": /^\\xt\s*/i},
	{"type": "XTA", "regex": /^\\xta\s*/i},
	{"type": "XOP", "regex": /^\\xop\*?\s*/i},
	{"type": "XOT", "regex": /^\\xot\*?\s*/i},
	{"type": "XNT", "regex": /^\\xnt\*?\s*/i},
	{"type": "XDC", "regex": /^\\xdc\*?\s*/i},
	{"type": "RQ", "regex": /^\\rq\*?\s*/i},
	// Words and Characters
	{"type": "ADD", "regex": /^\\add\*?\s*/i},
	{"type": "BK", "regex": /^\\bk\*?\s*/i},
	{"type": "DC", "regex": /^\\dc\*?\s*/i},
	{"type": "K", "regex": /^\\k\*?\s*/i},
	{"type": "LIT", "regex": /^\\lit\s*/i},
	{"type": "ND", "regex": /^\\nd\*?\s*/i},
	{"type": "ORD", "regex": /^\\ord\*?\s*/i},
	{"type": "PN", "regex": /^\\pn\*?\s*/i},
	{"type": "PNG", "regex": /^\\png\*?\s*/i},
	{"type": "ADDPN", "regex": /^\\addpn\*?\s*/i},
	{"type": "QT", "regex": /^\\qt\*?\s*/i},
	{"type": "SIG", "regex": /^\\sig\*?\s*/i},
	{"type": "SLS", "regex": /^\\sls\*?\s*/i},
	{"type": "TL", "regex": /^\\tl\*?\s*/i},
	{"type": "WJ", "regex": /^\\wj\*?\s*/i},
	// Character styling
	{"type": "EM", "regex": /^\\em\*?\s*/i},
	{"type": "BD", "regex": /^\\bd\*?\s*/i},
	{"type": "IT", "regex": /^\\it\*?\s*/i},
	{"type": "BDIT", "regex": /^\\bdit\*?\s*/i},
	{"type": "NO", "regex": /^\\no\*?\s*/i},
	{"type": "SC", "regex": /^\\sc\*?\s*/i},
	{"type": "SUP", "regex": /^\\sup\*?\s*/i},
	// Spacing and breaks
	{"type": "NBSP", "regex": /^\\~\s*/i},
	{"type": "BR", "regex": /^\\\/\/\s*/i},
	{"type": "PB", "regex": /^\\pb\s*/i},
	// Special features
	{"type": "FIG", "regex": /^\\fig\*?\s*/i},
	{"type": "NDX", "regex": /^\\ndx\*?\s*/i},
	{"type": "RB", "regex": /^\\rb\*?\s*/i},
	{"type": "PRO", "regex": /^\\pro\*?\s*/i},
	{"type": "W", "regex": /^\\w\*?\s*/i},
	{"type": "WG", "regex": /^\\wg\*?\s*/i},
	{"type": "WH", "regex": /^\\wh\*?\s*/i},
	{"type": "WA", "regex": /^\\wa\*?\s*/i},
	// Linking Attributes
	{"type": "JMP", "regex": /^\\jmp\*?\s*/i},
}